[general]
title = "Difusor de Aromas"
logo = ""
iconLogo = "tabler:leaf"

[general.seo]
name = "Difusores de Aromas"
description = "Descubre los mejores difusores de aromas, aceites esenciales y consejos para transformar tu hogar en un espacio de bienestar."
url = "https://difusoraromas.com"

[directory.search]
placeholder = "Busca entre {0} difusores y accesorios"
showCount = true
icon = "tabler:search"

[directory.search.tags]
display = "select"   # options: none,select,show-all
intersection = false

[directory.grid]
list = false

[directory.grid.emptyState]
text = "Parece que no encontramos ese producto en nuestra colección."
type = "button"                                              # options: button, simple, link
icon = "tabler:exclamation-mark"

[directory.grid.card]
image = true
border = "shadow" # options: dashed, shadow, outline

[directory.grid.submit]
show = true
first = false
title = "¿Falta un difusor?"
description = "Envíanos sugerencias para ampliar nuestra colección de difusores y aromas."
hideable = true

[directory.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Recomendado ✨"

[directory.tagPages]
title = "Difusores para {0}"

[[directory.tags]]
key = "electricos"
name = "Difusores Eléctricos"
color = "blue"

[[directory.tags]]
key = "vidrio"
name = "Difusores de Vidrio"
color = "green"


[[directory.tags]]
key = "aceites_esenciales"
name = "Aceites Esenciales"
color = "yellow"

[[directory.tags]]
key = "madera"
name = "Difusores de Madera"
color = "brown"

[[directory.tags]]
key = "relajacion"
name = "Relajación"
color = "purple"

[header.banner]
show = true
text = "Síguenos para más tips sobre bienestar y aromaterapia."
link = "https://x.com/intent/follow?screen_name=difusoraromas"
brandText = "Aromaterapia y Bienestar"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Tienda"
href = "/tienda"
target = "_self"

[[header.navbar.links]]
name = "Blog"
href = "/blog"
target = "_self"

[[header.navbar.links]]
name = "Contactar"
href = "/contacto"
target = "_self"

[header.actionButton]
text = "Explora nuestros productos"
href = "/productos"

[footer]
description = "El lugar ideal para encontrar los mejores difusores de aromas, aceites esenciales y consejos de bienestar."

[footer.socials.github]
link = ""
icon = "tabler:brand-github"

[footer.socials.facebook]
link = "https://www.facebook.com/difusoraromas"
icon = "tabler:brand-facebook"

[footer.socials.instagram]
link = "https://www.instagram.com/difusoraromas"
icon = "tabler:brand-instagram"

[footer.socials.x]
link = "https://x.com/difusoraromas"
icon = "tabler:brand-twitter"

[footer.socials.youtube]
link = "https://www.youtube.com/@difusoraromas"
icon = "tabler:brand-youtube"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
